# Generated by Django 3.2 on 2021-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
